(()=>{'use strict';
const K='examforge.activity.v2',$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const more=[
{id:'m6',subject:'DSA',difficulty:'Easy',q:'Which operation removes the top stack element?',options:['Push','Pop','Peek','Insert'],correct:1,explain:'Pop removes the top stack element.'},
{id:'m7',subject:'DSA',difficulty:'Medium',q:'Binary search on a sorted array takes:',options:['O(1)','O(log n)','O(n)','O(n²)'],correct:1,explain:'Binary search halves the search range each step.'},
{id:'m8',subject:'DSA',difficulty:'Hard',q:'Dijkstra’s algorithm requires edge weights to be:',options:['Negative','Non-negative','Equal','Prime'],correct:1,explain:'Standard Dijkstra requires non-negative weights.'},
{id:'m9',subject:'Mathematics',difficulty:'Easy',q:'Solve 2x + 6 = 14.',options:['2','3','4','5'],correct:2,explain:'2x=8, therefore x=4.'},
{id:'m10',subject:'Mathematics',difficulty:'Medium',q:'Probability of two heads in two fair tosses is:',options:['1/2','1/3','1/4','3/4'],correct:2,explain:'HH is one of four equally likely outcomes.'},
{id:'m11',subject:'Python',difficulty:'Easy',q:'Which Python type is immutable?',options:['list','dict','set','tuple'],correct:3,explain:'Tuple is immutable.'},
{id:'m12',subject:'Python',difficulty:'Medium',q:'__init__ is commonly used for:',options:['Importing modules','Initializing objects','Ending loops','Deleting classes'],correct:1,explain:'__init__ initializes an instance.'},
{id:'m13',subject:'SQL',difficulty:'Easy',q:'Which SQL function counts rows?',options:['SUM()','COUNT()','TOTAL()','NUMBER()'],correct:1,explain:'COUNT() returns a row/value count.'},
{id:'m14',subject:'SQL',difficulty:'Medium',q:'A primary key must be:',options:['Nullable','Unique and non-null','Text only','A foreign key'],correct:1,explain:'A primary key uniquely identifies a row and cannot be null.'}
];
const bank=[...(typeof mcqs==='undefined'?[]:mcqs).map((q,i)=>({id:q.id||'m'+(i+1),...q})),...more];
const fresh=()=>({version:2,activities:[],attempts:[],settings:{mode:'untimed',questionSeconds:30,testMinutes:5,testCount:10}});
let S;try{S={...fresh(),...JSON.parse(localStorage.getItem(K)||'null')}}catch(e){S=fresh()} if(!Array.isArray(S.activities))S.activities=[];if(!Array.isArray(S.attempts))S.attempts=[];
const save=()=>localStorage.setItem(K,JSON.stringify(S)),id=()=>Date.now()+'-'+Math.random().toString(36).slice(2,7),log=(type,x={})=>{S.activities.unshift({id:id(),time:new Date().toISOString(),type,...x});S.activities=S.activities.slice(0,500);save()};
function mcqBank(){const b=$('#mcqBank');if(!b)return;b.innerHTML=bank.slice(0,12).map(q=>`<article class="mcq-card"><div class="question-meta"><span class="tag">${E(q.subject)}</span><span class="tag">${E(q.difficulty)}</span><span class="tag">MCQ</span></div><h3>${E(q.q)}</h3><div class="mcq-options">${q.options.map((o,i)=>`<div class="mcq-option"><strong>${String.fromCharCode(65+i)}.</strong> ${E(o)}</div>`).join('')}</div></article>`).join('')}mcqBank();
const mode=$('#testMode'),qs=$('#questionSeconds'),tm=$('#testMinutes'),cnt=$('#testCount'),qsl=$('#questionSecondsLabel'),tml=$('#testMinutesLabel');
if(mode)mode.value=S.settings.mode||'untimed';if(qs)qs.value=S.settings.questionSeconds||30;if(tm)tm.value=S.settings.testMinutes||5;if(cnt)cnt.value=S.settings.testCount||10;
function modeUI(){if(!mode)return;qsl.hidden=mode.value!=='question';tml.hidden=mode.value!=='test';S.settings={mode:mode.value,questionSeconds:+qs.value||30,testMinutes:+tm.value||5,testCount:+cnt.value||10};save()}[mode,qs,tm,cnt].forEach(x=>x&&x.addEventListener('change',modeUI));modeUI();
let T=null,tick=null;
const fmt=n=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`,setTimer=(lab,val,state='')=>{if($('#timerLabel'))$('#timerLabel').textContent=lab;if($('#timerValue'))$('#timerValue').textContent=val;if($('#timerBox'))$('#timerBox').className='timer-box '+state};
function clear(){if(tick)clearInterval(tick);tick=null}
function pool(){const s=$('#practiceSubject')?.value||'',d=$('#practiceDifficulty')?.value||'';let a=bank.filter(q=>(!s||q.subject===s)&&(!d||q.difficulty===d));if(!a.length&&s)a=bank.filter(q=>q.subject===s);return a.sort(()=>Math.random()-.5)}
function start(){clear();let a=pool();if(!a.length){$('#practiceCard').innerHTML='<div class="empty-state">No MCQs match this filter.</div>';return}a=a.slice(0,Math.min(+cnt.value||10,a.length));T={id:id(),startedAt:new Date().toISOString(),subject:$('#practiceSubject')?.value||'Mixed',difficulty:$('#practiceDifficulty')?.value||'Mixed',mode:mode.value,qs:+qs.value||30,ts:(+tm.value||5)*60,questions:a,i:0,score:0,answered:0,responses:[]};if(T.mode==='test')T.deadline=Date.now()+T.ts*1000;if(T.mode==='question')T.qdeadline=Date.now()+T.qs*1000;log('test_started',{testId:T.id,subject:T.subject,mode:T.mode,count:a.length});render();clock()}
function clock(){clear();if(!T||T.mode==='untimed'){setTimer('Untimed','—');return}const run=()=>{if(!T)return clear();let target=T.mode==='question'?T.qdeadline:T.deadline,n=Math.max(0,Math.ceil((target-Date.now())/1000));setTimer(T.mode==='question'?'Question time':'Test time',fmt(n),n<=10?'danger':n<=30?'warning':'');if(n<=0){clear();T.mode==='question'?answer(null,true):finish('time_expired')}};run();tick=setInterval(run,250)}
function render(){if(!T)return;if(T.i>=T.questions.length)return finish('completed');const q=T.questions[T.i];$('#practiceCard').innerHTML=`<div class="test-head"><span class="eyebrow">QUESTION ${T.i+1} OF ${T.questions.length}</span><span class="pill">${E(q.subject)} • ${E(q.difficulty)}</span></div><h2>${E(q.q)}</h2><div>${q.options.map((o,i)=>`<button class="answer" data-a="${i}"><strong>${String.fromCharCode(65+i)}.</strong> ${E(o)}</button>`).join('')}</div><div id="practiceExplain"></div>`;$('#practiceScore').textContent=`${T.score} / ${T.answered}`;$('#questionProgress').textContent=`Question ${T.i+1} of ${T.questions.length}`;$('#testProgress').max=T.questions.length;$('#testProgress').value=T.i;$$('[data-a]').forEach(b=>b.onclick=()=>answer(+b.dataset.a,false))}
function answer(c,to=false){if(!T)return;const q=T.questions[T.i],ok=!to&&c===q.correct;T.answered++;if(ok)T.score++;T.responses.push({questionId:q.id,choice:to?null:c,correct:ok,timedOut:to});$$('[data-a]').forEach((b,i)=>{b.disabled=true;if(i===q.correct)b.classList.add('correct');else if(!to&&i===c)b.classList.add('wrong')});$('#practiceScore').textContent=`${T.score} / ${T.answered}`;$('#practiceExplain').innerHTML=`<div class="explanation"><strong>${to?'Time expired':ok?'Correct':'Incorrect'}</strong><p>${E(q.explain)}</p><button class="btn primary" id="nx">${T.i+1>=T.questions.length?'Finish Test':'Next Question'}</button></div>`;log('question_answered',{testId:T.id,questionId:q.id,correct:ok,timedOut:to});if(T.mode==='question')clear();$('#nx').onclick=next;if(to)setTimeout(()=>T&&next(),800)}
function next(){if(!T)return;T.i++;if(T.i>=T.questions.length)return finish('completed');if(T.mode==='question')T.qdeadline=Date.now()+T.qs*1000;render();clock()}
function finish(reason){if(!T)return;clear();const p=Math.round(100*T.score/T.questions.length),A={...T,finishedAt:new Date().toISOString(),reason,percentage:p};delete A.deadline;delete A.qdeadline;S.attempts.unshift(A);S.attempts=S.attempts.slice(0,200);log('test_finished',{testId:T.id,score:T.score,total:T.questions.length,percentage:p,mode:T.mode});$('#practiceCard').innerHTML=`<span class="eyebrow">TEST COMPLETE</span><h2>${p}%</h2><div class="test-summary"><div><strong>${T.score}/${T.questions.length}</strong><span>Score</span></div><div><strong>${p}%</strong><span>Percentage</span></div><div><strong>${T.responses.filter(r=>r.timedOut).length}</strong><span>Timed out</span></div></div><p>Your result has been saved in local storage.</p><div class="hero-actions"><button class="btn primary" id="again">Try Another Test</button><a class="btn secondary" href="#dashboard">View Saved History</a></div>`;$('#practiceScore').textContent=`${T.score} / ${T.questions.length}`;$('#questionProgress').textContent='Complete';$('#testProgress').value=T.questions.length;setTimer('Finished','00:00');T=null;dash();$('#again').onclick=start}
if($('#newPractice'))$('#newPractice').onclick=start;if($('#practiceSubject'))$('#practiceSubject').onchange=()=>{};if($('#practiceDifficulty'))$('#practiceDifficulty').onchange=()=>{};if($('#practiceCard'))$('#practiceCard').innerHTML='<div class="empty-state"><div><strong>Choose your test settings.</strong><p>Then press Start New Test.</p></div></div>';
const name=m=>m==='question'?'Per-question timer':m==='test'?'Whole-test timer':'Untimed';
function dash(){const a=S.attempts,n=a.length,avg=n?Math.round(a.reduce((s,x)=>s+(x.percentage||0),0)/n):0,best=n?Math.max(...a.map(x=>x.percentage||0)):0,solved=a.reduce((s,x)=>s+(x.responses?.length||0),0);if($('#dashboardContent')&&($('#dashboard .segmented .active')?.dataset.role||'student')==='student')$('#dashboardContent').innerHTML=`<div class="dashboard-grid"><article class="metric-card"><strong>${avg}%</strong><span>Average score</span></article><article class="metric-card"><strong>${n}</strong><span>Tests attempted</span></article><article class="metric-card"><strong>${solved}</strong><span>MCQs answered</span></article><article class="metric-card"><strong>${best}%</strong><span>Best score</span></article></div><div class="local-note">These figures come from this browser's local ExamForge history.</div>`;if($('#historyCount'))$('#historyCount').textContent=`${n} attempt${n===1?'':'s'}`;if($('#activityHistory'))$('#activityHistory').innerHTML=n?a.slice(0,30).map(x=>`<article class="activity-row"><div><h3>${E(x.subject)} • ${name(x.mode)}</h3><p>${new Date(x.finishedAt||x.startedAt).toLocaleString()} • ${x.questions?.length||0} questions • ${E(x.difficulty)}</p></div><div class="activity-score"><strong>${x.score}/${x.questions?.length||0}</strong><span>${x.percentage||0}%</span></div></article>`).join(''):'<div class="empty-state"><div><strong>No saved attempts yet.</strong><p>Complete a test and it will appear here.</p></div></div>'}$$('[data-role]').forEach(b=>b.addEventListener('click',()=>setTimeout(dash,0)));dash();
function download(){log('data_exported',{attempts:S.attempts.length});const blob=new Blob([JSON.stringify({app:'ExamForge',exportedAt:new Date().toISOString(),...S},null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='examforge-activity-'+new Date().toISOString().replace(/[:.]/g,'-')+'.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
async function upload(f){try{const x=JSON.parse(await f.text());if(!Array.isArray(x.attempts)||!Array.isArray(x.activities))throw Error('Not a valid ExamForge backup');const am=new Map([...S.attempts,...x.attempts].map(v=>[v.id||id(),v])),gm=new Map([...S.activities,...x.activities].map(v=>[v.id||id(),v]));S.attempts=[...am.values()].sort((a,b)=>new Date(b.finishedAt||b.startedAt)-new Date(a.finishedAt||a.startedAt));S.activities=[...gm.values()].sort((a,b)=>new Date(b.time)-new Date(a.time));S.settings={...S.settings,...(x.settings||{})};log('data_imported',{attempts:x.attempts.length});save();dash();openModal(`<h2>Activity restored</h2><p>Imported ${x.attempts.length} test attempt(s). Existing history was preserved.</p>`)}catch(e){openModal(`<h2>Import failed</h2><p>${E(e.message)}</p>`)}}
$('#downloadData')?.addEventListener('click',download);$('#uploadData')?.addEventListener('click',()=>{$('#activityFile').value='';$('#activityFile').click()});$('#activityFile')?.addEventListener('change',e=>e.target.files?.[0]&&upload(e.target.files[0]));
const op=window.openPaper;if(typeof op==='function')window.openPaper=i=>{log('paper_opened',{paperId:i});return op(i)};const rm=window.remixPaper;if(typeof rm==='function')window.remixPaper=i=>{log('paper_remixed',{paperId:i});return rm(i)};$('#paperForm')?.addEventListener('submit',()=>log('paper_generated',{subject:$('#newSubject')?.value,title:$('#newTitle')?.value}));
})();