(()=>{'use strict';
const $=id=>document.getElementById(id);const KEY='up-naukri-guru.demo.v1';
const exams=['UP Police','UPSSSC PET','Lekhpal','VDO','UP TET'];
const q=(id,exam,topic,difficulty,text,options,answer,explanation)=>({id,exam,topic,difficulty,text,options,answer,explanation});
const questions=[
q(1,'UP Police','Reasoning','Easy','Which number comes next: 2, 4, 8, 16, ?',['18','24','32','36'],2,'Each term is doubled.'),
q(2,'UP Police','Mathematics','Easy','What is 15% of 200?',['20','25','30','35'],2,'15/100 × 200 = 30.'),
q(3,'UP Police','General Knowledge','Easy','The Constitution of India came into effect on:',['15 August 1947','26 January 1950','26 November 1949','2 October 1950'],1,'The Constitution came into force on 26 January 1950.'),
q(4,'UP Police','Reasoning','Medium','If CAT is coded as DBU by shifting every letter forward once, DOG becomes:',['EPH','ENH','FPH','EOG'],0,'D→E, O→P and G→H.'),
q(5,'UP Police','Mathematics','Medium','A vehicle covers 120 km in 3 hours. Its average speed is:',['30 km/h','40 km/h','45 km/h','60 km/h'],1,'Speed = distance ÷ time = 120 ÷ 3.'),
q(6,'UPSSSC PET','Mathematics','Easy','What is the average of 10, 20 and 30?',['15','20','25','30'],1,'(10+20+30) ÷ 3 = 20.'),
q(7,'UPSSSC PET','Reasoning','Easy','Choose the odd one out.',['Square','Triangle','Circle','Rectangle'],2,'Circle has no straight sides.'),
q(8,'UPSSSC PET','General Knowledge','Easy','How many Fundamental Duties are currently listed in the Indian Constitution?',['9','10','11','12'],2,'There are 11 Fundamental Duties.'),
q(9,'UPSSSC PET','Hindi','Medium','“जल” का पर्यायवाची कौन-सा है?',['अग्नि','नीर','वायु','धरती'],1,'नीर, जल का पर्यायवाची है।'),
q(10,'UPSSSC PET','Mathematics','Medium','If a number is increased from 80 to 100, the percentage increase is:',['20%','25%','30%','40%'],1,'Increase is 20; 20/80 ×100 = 25%.'),
q(11,'Lekhpal','Mathematics','Easy','A field is 20 m long and 10 m wide. Its area is:',['30 m²','100 m²','200 m²','400 m²'],2,'Area = length × width.'),
q(12,'Lekhpal','General Knowledge','Easy','Panchayati Raj is primarily associated with:',['Local self-government','Foreign trade','Defence','Banking'],0,'Panchayati Raj is a system of rural local self-government.'),
q(13,'Lekhpal','Hindi','Easy','“लाभ” का विलोम शब्द है:',['हानि','धन','आय','सुख'],0,'लाभ का विलोम हानि है।'),
q(14,'Lekhpal','Reasoning','Medium','If all pens are stationery and some stationery is blue, which is definitely true?',['All pens are blue','Some pens are blue','Pens are stationery','No stationery is blue'],2,'The only guaranteed statement is that pens are stationery.'),
q(15,'Lekhpal','Mathematics','Medium','Simple interest on ₹1000 at 10% per year for 2 years is:',['₹100','₹150','₹200','₹250'],2,'SI = P×R×T/100 = 1000×10×2/100.'),
q(16,'VDO','General Knowledge','Easy','Gram Sabha consists of:',['Only elected members','All registered voters in the village area','Only government officers','Only landowners'],1,'Gram Sabha comprises registered voters in the village area.'),
q(17,'VDO','Mathematics','Easy','3/4 expressed as a percentage is:',['25%','50%','75%','80%'],2,'3÷4 ×100 = 75%.'),
q(18,'VDO','Reasoning','Easy','Complete the series: A, C, E, G, ?',['H','I','J','K'],1,'The sequence skips one letter each time.'),
q(19,'VDO','Hindi','Medium','“प्रगति” का निकटतम अर्थ है:',['विकास','पतन','भय','विरोध'],0,'प्रगति का अर्थ विकास या उन्नति है।'),
q(20,'VDO','Mathematics','Medium','If 5 workers complete a task in 12 days at the same rate, total worker-days are:',['17','60','120','240'],1,'5 × 12 = 60 worker-days.'),
q(21,'UP TET','Pedagogy','Easy','A child-centred classroom primarily emphasizes:',['Only lecture','Learner participation','Memorising without discussion','Punishment'],1,'Child-centred learning emphasizes active learner participation.'),
q(22,'UP TET','Mathematics','Easy','What is 7 × 8?',['54','56','58','64'],1,'7 × 8 = 56.'),
q(23,'UP TET','Language','Easy','Which word is a noun?',['Quickly','Beautiful','Teacher','Run'],2,'Teacher names a person and is a noun.'),
q(24,'UP TET','Pedagogy','Medium','Formative assessment is mainly used to:',['Rank schools only','Improve learning during instruction','Replace teaching','Punish weak learners'],1,'Formative assessment provides feedback during the learning process.'),
q(25,'UP TET','Reasoning','Medium','If 4 books cost ₹200 equally, the cost of one book is:',['₹25','₹40','₹50','₹80'],2,'₹200 ÷ 4 = ₹50.')
];
const papers=[
{title:'UP Police — sample previous-paper view',exam:'UP Police',year:'2024',topics:'Reasoning • GK • Mathematics'},
{title:'UP Police — sample previous-paper view',exam:'UP Police',year:'2023',topics:'Reasoning • Hindi • GK'},
{title:'UPSSSC PET — sample previous-paper view',exam:'UPSSSC PET',year:'2023',topics:'GK • Hindi • Aptitude'},
{title:'UPSSSC PET — sample previous-paper view',exam:'UPSSSC PET',year:'2022',topics:'Reasoning • Mathematics • GK'},
{title:'Lekhpal — sample archive entry',exam:'Lekhpal',year:'2022',topics:'Rural Development • Hindi • Maths'},
{title:'Lekhpal — sample archive entry',exam:'Lekhpal',year:'2019',topics:'GK • Mathematics • Hindi'},
{title:'VDO — sample archive entry',exam:'VDO',year:'2023',topics:'Panchayat • Reasoning • Hindi'},
{title:'VDO — sample archive entry',exam:'VDO',year:'2018',topics:'GK • Mathematics • Hindi'},
{title:'UP TET — sample paper view',exam:'UP TET',year:'2021',topics:'Pedagogy • Language • Mathematics'},
{title:'UP TET — sample paper view',exam:'UP TET',year:'2019',topics:'Pedagogy • EVS • Language'}
];
let state=load();let practiceSet=[],practiceIndex=0,practiceCorrect=0,practiceAnswered=0,practiceStreak=0;let mockSet=[],mockAnswers={},mockIndex=0,mockSeconds=300,mockInterval=null,mockActive=false;
function load(){try{return Object.assign({exam:'UPSSSC PET',activity:[],topicStats:{}},JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return{exam:'UPSSSC PET',activity:[],topicStats:{}}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function addActivity(type,detail){state.activity.unshift({type,detail,exam:state.exam,at:new Date().toISOString()});state.activity=state.activity.slice(0,80);save()}
function recordTopic(question,correct){const k=question.topic;state.topicStats[k]??={right:0,total:0};state.topicStats[k].total++;if(correct)state.topicStats[k].right++;save()}
function setExam(exam){state.exam=exam;save();document.querySelectorAll('[data-exam]').forEach(b=>b.classList.toggle('active',b.dataset.exam===exam));$('selectedExamLabel').textContent=`${exam} selected`;$('practiceExamPill').textContent=exam;$('mockExamPill').textContent=exam;$('todayTargetText').textContent=`Continue with ${exam} and aim for at least 80% accuracy.`;populatePracticeTopics();renderDashboard();toast(`${exam} selected`)}
function route(){const id=(location.hash||'#home').slice(1);document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));document.querySelectorAll('.main-nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${id}`));$('mainNav').classList.remove('open');$('menuBtn').setAttribute('aria-expanded','false');if(id==='dashboard')renderDashboard();if(id==='pyq')renderPapers();window.scrollTo({top:0,behavior:'smooth'})}
function populatePracticeTopics(){const pool=questions.filter(x=>x.exam===state.exam);const topics=[...new Set(pool.map(x=>x.topic))];$('practiceTopic').innerHTML='<option value="">All topics</option>'+topics.map(t=>`<option>${t}</option>`).join('')}
function startPractice(){let pool=questions.filter(x=>x.exam===state.exam);const t=$('practiceTopic').value,d=$('practiceDifficulty').value;if(t)pool=pool.filter(x=>x.topic===t);if(d)pool=pool.filter(x=>x.difficulty===d);practiceSet=shuffle(pool);practiceIndex=0;practiceCorrect=practiceAnswered=practiceStreak=0;renderPractice()}
function renderPractice(){const card=$('practiceCard');$('practiceScore').textContent=`${practiceCorrect} / ${practiceAnswered}`;$('practiceStreak').textContent=practiceStreak;if(!practiceSet.length){card.innerHTML='<div class="empty-state"><strong>No questions match these filters.</strong><p>Try another topic or difficulty.</p></div>';return}if(practiceIndex>=practiceSet.length){card.innerHTML=`<div class="empty-state"><strong>Practice complete</strong><p>You scored ${practiceCorrect} out of ${practiceAnswered}.</p><button class="btn primary" id="againPractice">Practise again</button></div>`;$('againPractice')?.addEventListener('click',startPractice);addActivity('Practice set',`${practiceCorrect}/${practiceAnswered}`);renderDashboard();return}const x=practiceSet[practiceIndex];card.innerHTML=`<div class="question-meta"><span class="tag">${x.topic}</span><span class="tag">${x.difficulty}</span><span class="tag">Question ${practiceIndex+1}/${practiceSet.length}</span></div><h2>${x.text}</h2><div class="options">${x.options.map((o,i)=>`<button class="option-btn" data-i="${i}" type="button">${String.fromCharCode(65+i)}. ${o}</button>`).join('')}</div><div id="practiceFeedback"></div><div class="question-actions"><button class="btn secondary" id="skipPractice" type="button">Skip</button><button class="btn primary" id="nextPractice" type="button" disabled>Next Question</button></div>`;let done=false;card.querySelectorAll('.option-btn').forEach(btn=>btn.addEventListener('click',()=>{if(done)return;done=true;const picked=Number(btn.dataset.i),ok=picked===x.answer;practiceAnswered++;if(ok){practiceCorrect++;practiceStreak++}else practiceStreak=0;recordTopic(x,ok);card.querySelectorAll('.option-btn').forEach((b,i)=>{b.disabled=true;if(i===x.answer)b.classList.add('correct');if(i===picked&&!ok)b.classList.add('wrong')});$('practiceFeedback').innerHTML=`<div class="feedback"><strong>${ok?'Correct':'Not quite'}.</strong> ${x.explanation}</div>`;$('nextPractice').disabled=false;$('practiceScore').textContent=`${practiceCorrect} / ${practiceAnswered}`;$('practiceStreak').textContent=practiceStreak}));$('skipPractice').addEventListener('click',()=>{practiceIndex++;renderPractice()});$('nextPractice').addEventListener('click',()=>{practiceIndex++;renderPractice()})}
function startMock(){clearInterval(mockInterval);mockSet=shuffle(questions.filter(x=>x.exam===state.exam)).slice(0,5);mockAnswers={};mockIndex=0;mockSeconds=300;mockActive=true;$('submitMockBtn').disabled=false;mockInterval=setInterval(()=>{mockSeconds--;renderMockTimer();if(mockSeconds<=0)submitMock(true)},1000);renderMock()}
function renderMockTimer(){const m=Math.floor(mockSeconds/60),s=mockSeconds%60;$('mockTimer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function renderMockNav(){const nav=$('mockNavigator');nav.innerHTML=mockSet.map((_,i)=>`<button type="button" data-i="${i}" class="${i===mockIndex?'active':''} ${mockAnswers[i]!=null?'answered':''}">${i+1}</button>`).join('');nav.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{mockIndex=Number(b.dataset.i);renderMock()}));$('mockAnswered').textContent=`${Object.keys(mockAnswers).length} / ${mockSet.length||5}`}
function renderMock(){renderMockTimer();renderMockNav();const card=$('mockCard');if(!mockActive||!mockSet.length){card.innerHTML='<div class="empty-state"><strong>Ready for a five-question demo mock?</strong><p>Press Start New Mock. The timer will begin at 5 minutes.</p></div>';return}const x=mockSet[mockIndex];card.innerHTML=`<div class="question-meta"><span class="tag">${x.topic}</span><span class="tag">Question ${mockIndex+1}/${mockSet.length}</span></div><h2>${x.text}</h2><div class="options">${x.options.map((o,i)=>`<label><input type="radio" name="mockAnswer" value="${i}" ${mockAnswers[mockIndex]===i?'checked':''}/><span>${String.fromCharCode(65+i)}. ${o}</span></label>`).join('')}</div><div class="question-actions"><button id="mockPrev" class="btn secondary" type="button" ${mockIndex===0?'disabled':''}>Previous</button><button id="mockNext" class="btn primary" type="button">${mockIndex===mockSet.length-1?'Review':'Next'}</button></div>`;card.querySelectorAll('input[name="mockAnswer"]').forEach(r=>r.addEventListener('change',()=>{mockAnswers[mockIndex]=Number(r.value);renderMockNav()}));$('mockPrev').addEventListener('click',()=>{if(mockIndex>0){mockIndex--;renderMock()}});$('mockNext').addEventListener('click',()=>{if(mockIndex<mockSet.length-1){mockIndex++;renderMock()}else toast('Review your answers, then submit the mock.')})}
function submitMock(timedOut=false){if(!mockActive)return;clearInterval(mockInterval);mockActive=false;let right=0;mockSet.forEach((x,i)=>{const ok=mockAnswers[i]===x.answer;if(ok)right++;if(mockAnswers[i]!=null)recordTopic(x,ok)});const pct=Math.round(right/mockSet.length*100);addActivity('Mock test',`${right}/${mockSet.length} (${pct}%)${timedOut?' — time ended':''}`);$('submitMockBtn').disabled=true;$('mockCard').innerHTML=`<div class="empty-state"><strong>Mock submitted: ${right}/${mockSet.length}</strong><p>${pct}% accuracy${timedOut?' — the timer reached zero.':''}</p><button class="btn primary" id="retryMock" type="button">Try another mock</button></div>`;$('retryMock')?.addEventListener('click',startMock);renderMockNav();renderDashboard()}
function initPaperFilters(){$('pyqExam').innerHTML='<option value="">All exams</option>'+exams.map(e=>`<option>${e}</option>`).join('');$('pyqYear').innerHTML='<option value="">All years</option>'+[...new Set(papers.map(p=>p.year))].sort().reverse().map(y=>`<option>${y}</option>`).join('')}
function renderPapers(){const e=$('pyqExam').value,y=$('pyqYear').value,s=$('pyqSearch').value.toLowerCase();const list=papers.filter(p=>(!e||p.exam===e)&&(!y||p.year===y)&&(!s||`${p.title} ${p.topics} ${p.year}`.toLowerCase().includes(s)));$('pyqList').innerHTML=list.length?list.map(p=>`<article class="paper-card"><div><div class="paper-meta"><span class="tag">${p.exam}</span><span class="tag">${p.year}</span><span class="tag">Demo archive entry</span></div><h3>${p.title}</h3><p>${p.topics}</p></div><a class="btn secondary" href="#practice">Practise related topics</a></article>`).join(''):'<div class="empty-state">No archive entries match these filters.</div>'}
function renderDashboard(){const acts=state.activity;let tests=0,totalPct=0;acts.forEach(a=>{if(a.type==='Mock test'){tests++;const m=a.detail.match(/\((\d+)%\)/);if(m)totalPct+=Number(m[1])}});const stats=Object.values(state.topicStats);const answered=stats.reduce((n,x)=>n+x.total,0),right=stats.reduce((n,x)=>n+x.right,0),accuracy=answered?Math.round(right/answered*100):0,avg=tests?Math.round(totalPct/tests):0;$('dashboardStats').innerHTML=[['Questions answered',answered],['Practice accuracy',`${accuracy}%`],['Mocks completed',tests],['Average mock',`${avg}%`]].map(([a,b])=>`<article class="stat-card"><span>${a}</span><strong>${b}</strong></article>`).join('');const rows=Object.entries(state.topicStats).sort((a,b)=>(a[1].right/a[1].total)-(b[1].right/b[1].total));$('topicPerformance').innerHTML=rows.length?rows.map(([name,v])=>{const pct=Math.round(v.right/v.total*100);return `<div class="progress-row"><div class="progress-row-head"><strong>${name}</strong><span>${pct}% (${v.right}/${v.total})</span></div><div class="bar"><span style="width:${pct}%"></span></div></div>`}).join(''):'<div class="empty-state">Answer practice questions to see weak-topic tracking.</div>';$('activityCount').textContent=`${acts.length} entries`;$('recentActivity').innerHTML=acts.length?acts.slice(0,8).map(a=>`<div class="activity-item"><strong>${a.type}</strong><div>${a.exam} — ${a.detail}</div><small>${new Date(a.at).toLocaleString()}</small></div>`).join(''):'<div class="empty-state">Your activity will appear here.</div>'}
function init(){window.addEventListener('hashchange',route);$('menuBtn').addEventListener('click',()=>{const n=$('mainNav');n.classList.toggle('open');$('menuBtn').setAttribute('aria-expanded',n.classList.contains('open'))});document.querySelectorAll('[data-exam]').forEach(b=>b.addEventListener('click',()=>setExam(b.dataset.exam)));$('newPracticeBtn').addEventListener('click',startPractice);$('startMockBtn').addEventListener('click',startMock);$('submitMockBtn').addEventListener('click',()=>submitMock(false));['pyqExam','pyqYear'].forEach(id=>$(id).addEventListener('change',renderPapers));$('pyqSearch').addEventListener('input',renderPapers);$('resetProgressBtn').addEventListener('click',()=>{if(confirm('Reset all locally saved demo progress?')){state.activity=[];state.topicStats={};save();renderDashboard();toast('Demo progress reset')}});let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('installBtn').hidden=false});async function install(){if(deferred){deferred.prompt();await deferred.userChoice;deferred=null}else toast('Use your browser menu and choose Install app / Add to Home screen.')} $('installBtn').addEventListener('click',install);$('installCardBtn').addEventListener('click',install);if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');initPaperFilters();setExam(state.exam);startPractice();renderMock();renderPapers();route()}
init();
})();
